AC_GAME_LIST = [
    "IIDX(SP)",
    "IIDX(DP)",
    "SDVX(通常)",
    "SDVX(EXスコア)",
    "jubeat",
    "pop'n music",
    "DDR(SP)",
    "DDR(DP)",
    "DrumMania",
    "ノスタルジア",
    "CHUNITHM",
    "maimai",
    "オンゲキ",
    "Project DIVA",
    "太鼓の達人",
    "ポラリスコード",
]
CS_GAME_LIST = [
    "Arcaea",
    "プロセカ",
    "ユメステ(通常)",
    "ユメステ(OLIVIER)",
    "DEEMO",
    "Cytus",
    "Cytus II",
    "VOEZ",
    "Lanota",
    "ガルパ",
    "D4DJ Groovy Mix",
    "Dynamix",
    "Phigros",
    "Muse Dash",
    "Tone Sphere",
    "Rotaeno",
    "TAKUMI³",
    "OverRapid",
    "BMS",
]

CIRCLE_LIST = ["B4UT", "京音", "EÜST’", "とんえぼ", "QUaver", "XyHUtte", "Wuv NU"]
